@echo off
rem A program to duplicate Squidgy
echo ษอออออออออออออออออออออออออป
echo บ Squidgy Round The World บ
echo วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
echo บ    Duplicating  Now     บ
echo ศอออออออออออออออออออออออออผ
echo Copying batch files
copy play.bat %1 	>nul
copy dup.bat %1     >nul
echo Copying Program files
copy choice.exe %1  >nul
copy squidgy.exe %1 >nul
copy demo.exe %1    >nul
copy editor.exe %1  >nul
copy paint1.exe %1  >nul
echo Copying Resource files
copy egavga.bgi %1  >nul
copy choice.cfg %1  >nul
copy mono.cfg %1    >nul
copy Lives.sym %1	>nul
echo Copying Level files
copy level*.mz4 %1 >nul
echo Copying Graphics files
copy supp.sym %1 	>nul
copy numbers.sym %1	>nul
copy graph*.sym %1 >nul
echo ษอออออออออออออออออออออออออป
echo บ Squidgy Round The World บ
echo วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
echo บ   Copying is complete   บ
echo ศอออออออออออออออออออออออออผ